{% set name = "xvec" %}
{% set version = "0.5.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xvec-{{ version }}.tar.gz
  sha256: ac4af0e4a5ffd3fadcc4fcf927746b528872dc851378dd431a683de1584e0a14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - xarray >=2022.12.0
    - pyproj >=3.0.0
    - shapely >=2.0b1
    - cf_xarray >=0.9.2
    - xproj >=0.2.0

test:
  imports:
    - xvec
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xarray-contrib/xvec
  summary: Vector data cubes for Xarray
  description: |
    Xvec combines Xarray n-D arrays and shapely 2 planar vector geometries
    to create a support for vector data cubes in Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://xvec.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/xvec

extra:
  recipe-maintainers:
    - martinfleis
